version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx  # 挂载Nginx日志目录
    restart: always
    environment:
      - TZ=Asia/Shanghai
  web:
    build: .
    ports:
      - "8000:8000"
    #command: daphne -b 0.0.0.0 -p 8000 device_manager.asgi:application
    env_file:
      - .env
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DJANGO_DEBUG}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}
      - TZ=Asia/Shanghai
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles  # 匹配原有STATIC_ROOT配置
      - ./logs/web:/app/logs  # 挂载日志目录
      - ./logs/django:/app/devices/var  # 挂载Django日志目录
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--deploy"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./logs/redis:/data/logs  # 挂载Redis日志目录
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PASSWORD}  # 添加密码启动参数
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-mysql:
    image: alpine:latest
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: sh -c "chown -R 999:999 /var/lib/mysql"
    user: root

  db:
    depends_on:
      - init-mysql
    image: mariadb:11.3
    healthcheck:
      test: ["CMD", "mariadb", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-h", "localhost", "-P", "3306", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai

    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql  # 挂载MySQL日志目录

volumes:
  redis_data:
  static_volume: